name: Process new comment on issue

on: 
  issue_comment:
    types: [created]

jobs:
  wti:
    name: Run wti
    runs-on: windows-2022
    permissions:
      issues: write
    if: ${{ !github.event.issue.pull_request && github.event.issue.user.id == github.event.comment.user.id }}
    steps: 
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - uses: ./.github/actions/triage
          with: 
              issue: '${{ github.event.issue.number }}'
              comment: '${{ github.event.comment.id }}'
              token: ${{ secrets.GITHUB_TOKEN }}