name: GitGudSimilarIssues comments

on:
  issues:
    types: [opened]

jobs:
  getSimilarIssues:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.getBody.outputs.message }}
    steps:
      - uses: actions/checkout@v2
      - id: getBody
        uses: craigloewen-msft/GitGudSimilarIssues@main
        with:
          issueTitle: ${{ github.event.issue.title }}
          repository: ${{ github.repository }}
          similarityTolerance: "0.7"
  add-comment:
    needs: getSimilarIssues
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --repo "$REPO" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          BODY: ${{ needs.getSimilarIssues.outputs.message }}
